modLoader = "javafml"
loaderVersion = "[${neoforge_loader_version},)"
issueTrackerURL = "${issues}"
license = "${license}"

[[mods]]
modId = "${modid}"
version = "${version}"
displayName = "${display_name}"
displayUrl="${homepage}"
authors = "${authors}"
credits="Based on DragNSounds API"
description = '''${description}'''
logoFile = "${icon}"

[[dependencies.${modid}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_dependency_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modid}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},${next_unsupported_minecraft_version})"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modid}]]
modId = "dragonlib"
type = "required"
versionRange = "[${dragonlib_version},)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.${modid}]]
modId = "dragnsounds"
type = "required"
versionRange = "[${dragnsounds_version},)"
ordering = "BEFORE"
side = "BOTH"
